### PR TITLE
express 404 now just proxies to base handler

### PR DESCRIPTION
**Pull request by p-mcgowan**
express 404 can be handled by the base exception handler

Couldn't figure out when domain 404 was used so I deleted it, but if it's still used then we can do the same thing as the express 404 handler.

Removed middlewareErrorHandling.ts as that is now in applicationMiddleware.ts

### CODE REVIEW

**Comment by Acrontum-Carmichael** [comment]
here is a use case - id requested, could not be found, 404 thrown. This could be offset to the async validator, but a 404 will need to be thrown there.

```
  /**
   * Operation ID: itemUniqueItemNameGet
   * Summary: Fetch an item
   * Description: Fetches the full item object by item uuid passed in the path
   */
  public async itemNameUniqueItemNameGet (
    jwtData: JwtAccess | undefined,
    params: ItemNameUniqueItemNameGetPath,
  ): Promise<Item> {
    const item = await ItemRepository.model.findOne({
      uniqueItemName: params.uniqueItemName,
      deletedAt: null,
    });
    if (!item) {
      throw http404();
    }
    return item.toObject();
  }
```

**Comment by p-mcgowan** [comment]
Ah, yeah that is handled by the default exception filter then. So any thrown error will go through the base handler.

We could also catch `err instanceof customError` and convert it into our own, but since they are deprecated it may not be necessary

**Comment by p-mcgowan** [comment]
Ah no I see now - you're correct, the http4xx codes are not handled by default.

what about converting them? something like `err instanceof customError) ? new exceptionFromError()`

**Comment by p-mcgowan** [comment]
something like this monster would do - catch custom-errors before they hit the middleware, convert to httpException
```typescript
import { requestMiddleware, responseMiddleware, handleHttpException, handleValidationErrors } from '@/http/nodegen/middleware';
import routesImporter from '@/http/nodegen/routesImporter';
import express from 'express';
// @ts-ignore (except the eslint one)
import customError from 'custom-error';
import http401 from '@/http/nodegen/errors/401';
import http403 from '@/http/nodegen/errors/403';
import http404 from '@/http/nodegen/errors/404';
import http406 from '@/http/nodegen/errors/406';
import http409 from '@/http/nodegen/errors/409';
import http410 from '@/http/nodegen/errors/410';
import http422 from '@/http/nodegen/errors/422';
import http423 from '@/http/nodegen/errors/423';
import http429 from '@/http/nodegen/errors/429';
import { HttpException } from '@/http/nodegen/errors';

const convertCustomToClass = (err: any, req: express.Request, res: express.Response, next: express.NextFunction) => {
  if (err instanceof http401) {
    return next(new HttpException(401));
  } else if (err instanceof http403) {
    return next(new HttpException(403));
  } else if (err instanceof http404) {
    return next(new HttpException(404));
  } else if (err instanceof http406) {
    return next(new HttpException(406));
  } else if (err instanceof http409) {
    return next(new HttpException(409));
  } else if (err instanceof http410) {
    return next(new HttpException(410));
  } else if (err instanceof http422) {
    return next(new HttpException(422));
  } else if (err instanceof http423) {
    return next(new HttpException(423));
  } else if (err instanceof http429) {
    return next(new HttpException(429));
  } else if (err instanceof customError) {
    return next(new HttpException(500));
  }
};

/**
 * Returns a promise allowing the server or cli script to know
 * when the app is ready; eg database connections established
 */
export default (): Promise<express.Express> => {
  return new Promise((resolve, reject) => {
    // Here is a good place to connect to databases if required,
    // resolve once connected else reject
    const app = express();

    requestMiddleware(app);
    routesImporter(app);

    app.use(convertCustomToClass);
    responseMiddleware(app);
    return resolve(app);
  });
};
```

that's a workaround if you do it manually, but we could plug that into the old handlers instead

**Comment by p-mcgowan** [comment]
added a custom-error handler which just converts to the new class and passes the error along

**Comment by Acrontum-Carmichael** [comment]
- if we remove/change the `src/http/middlewareErrorHandling.ts` right now we have no way of letting people why it is broken nor how to fix it.
- at this point it might be best to leave the handleDomain404 in play

we talked previously (granted with haste as the CS arena awaited :)) the idea of a roadmap to moving all these into the controllled layer in this case into the nodegen folder. Once this is done there is a lot more freedom to change a lot of things. Folk can always import their own additional middlewares into the app.ts directly.. could do with roadmap at this point

**Comment by Acrontum-Carmichael** [comment]
or even easier.. change the rc file so the nodegenDir points simply to http not http/nodegen. At that point we can then also drop the subdir nodegen which is making my face itch these days

**Comment by p-mcgowan** [comment]
Yeah I think it would be cool to use http instead of http/nodegen - right now it is basically the separation between replaceable and not, so we would have to figure out how to deal with that, but I like the idea.

`src/http/middlewareErrorHandling.ts` is no longer used, I just forgot to remove it with the HttpError refactor - the same code is just moved into `nodegen/middleware/applicationMiddleware.ts(responseMiddleware)`, but if they don't regenerate app.ts then it will certainly cause issues.

I would be happy to keep domain404, but just modify it to do the error conversion. I went with the rename since, with the new edit, it handles all custom-errors instead of just 404, but let me know what you think

**Comment by p-mcgowan** [comment]
The whole interface idea with domains works really way as a method of informing the user of changes - and realistically if we delete a file the build process will still tell the user, but I think that will always happen to some degree

**Comment by p-mcgowan** [comment]
change base and rebase off dev

**Pull request merged**
