### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by SergiAcrontum**
Fix for https://github.com/acrontum/generate-it-typescript-server/issues/74

### CODE REVIEW

**Comment by Acrontum-Carmichael** [comment]
looks good to me - what do you think @p-mcgowan ?

**Comment by p-mcgowan** [comment]
yup - looks good to me

**Comment by Acrontum-Carmichael** [comment]
Merged into develop @srmico could you run this in your API by pegging to the develop branch - if no issues we'll get it merged into master.

**Comment by SergiAcrontum** [comment]
@Acrontum-Carmichael it's all working fine :+1:

**Pull request merged**
