### PR TITLE
Fixed issue, closes #76

### LINKED ISSUE #76: The asyncValidationMiddleware.ts has a bug that causes "unhandledPromiseRejection" error
The bug is on line 32 `throw next(e)` should just be `return next(e)` or simply `next(e)`.

### PR DESCRIPTION
**Pull request by SergiAcrontum**

### CODE REVIEW

**Comment by SergiAcrontum** [comment]
Fixed #76

**Comment by p-mcgowan** [comment]
try catch is a bit expensive - what about something like this?
`return parseValidators(req, asyncValidators).then(() => next()).catch((e) => next(e));`

**Review by Acrontum-Carmichael — APPROVED** [review]

**Comment by SergiAcrontum** [comment]
@p-mcgowan I think this is the most consistent with the rest of the code, as we are using more async/await, but sure

**Comment by Acrontum-Carmichael** [comment]
Pat is right yea.. i did not know the try catch was expensive but populating a variable is additional expense not required

**Comment by p-mcgowan** [comment]
Don't get me wrong, I tend to over-code-golf things, but functionally it's the same, but when you split it out this way

```typescript
return async (req: NodegenRequest, res: express.Response, next: express.NextFunction) => {
  try {
    await parseValidators(req, asyncValidators);
    return next();
  } catch (e) {
    return next(e);
  }
};
```

it becomes clearer that the async await is not bringing anything new to the table - it still returns a promise which rejects or resolves depending on the call.

Personally, unless it really improves readability, I tend to prefer promises simply because of cleaner error handling and preventing try {} catch on every function

**Comment by SergiAcrontum** [comment]
I agree, I only used async/await to be consistent. As to why i created the "error" variable is because i like to only have 1 return statement in my functions, which imo improves readability (specially in js), as i dont have to go through all return types to guess what the function returns. Personally, i would have written this

`return (req: NodegenRequest, res: express.Response, next: express.NextFunction) =>
    parseValidators(req, asyncValidators).then(() => next()).catch(e => next(e))
`
:D

**Comment by p-mcgowan** [comment]
For sure - and for the most part i agree with return once, but that doesn't work with the exit early pattern, or base case (for algorithms).

I tend to do the same (return once) when the return type from that point on is the same:
```typescript
if (!params.valid) {
  return null;  // or throw, doesnt matter
}

if (condtion.length < 10) {
  return input;
}

let output: any;

if (blah) output = firstThing;
...

return output;
```

**Comment by p-mcgowan** [comment]
Either way - this sounds like a good coffee machine convo.

PR looks good so we can merge 

@Acrontum-Carmichael any last words?

**Comment by Acrontum-Carmichael** [comment]
it is a managed layer so i don't mind either way.. imo is ugly :)
```
parseValidators(req, asyncValidators).then(() => next()).catch(e => next(e))
```
but we're splitting hairs here now down to opinion

imo this is better as the code san { } usually results in code you have to read with much more attention.. which results in bugs.. so this would have been preference..
```
parseValidators(req, asyncValidators).then(() => {
   next()
}).catch(e => {
  next(e)
})
```

would be interesting to run bench marks against the original code and the new code.. to know if either try/catch or then/catch is more expensive that the other. We would need to dig into the core of v8 to truly know though...

That being said, the only aspect there which was definitely redundant was the declaration of the "let" outside of the try/catch block.

**Comment by p-mcgowan** [comment]
Definitely more readable - the only thing to be careful about is not returning anything, as that can end up in unhandledRejection, but as I mentioned I tend to do more code golf solutions than readability ones, so I think the happiest path here would be 
```typescript
return parseValidators(req, asyncValidators).then(() => {
   return next()
}).catch(e => {
  return next(e)
})
```

**Pull request merged**
